version: '3'

tasks:
  default:
    cmds:
      - task prepare
      - task build
      
  build:
    cmds:
      - ./ocb --config builder-config.yml

  prepare:
    cmds:
      - |
        curl --proto '=https' --tlsv1.2 -fL -o ocb \
        https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv0.112.0/ocb_0.112.0_darwin_arm64
        chmod +x ocb

